server:
  port: 8081
#config spring boot application
spring:
  application:
    name: store-selling-products
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devs-test?serverTimezone=America/Mexico_City
    username: root
    password: root_123
    driver-class-name: com.mysql.cj.jdbc.Driver
